# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This is the Web
description: >
    What is the web? This is the web.
baseurl: ""
url: "https://thisistheweb.com"
twitter_username: _thisistheweb
permalink: "/:year/:month/:day/:title"

# Build settings
markdown: kramdown
